import type { SurahMeta } from './types.ts';

export const SURAH_META: readonly SurahMeta[] = [
  { number: 1, name: 'الفاتحة', englishName: 'Al-Fatiha', ayahCount: 7, revelationType: 'Meccan' },
  { number: 2, name: 'البقرة', englishName: 'Al-Baqara', ayahCount: 286, revelationType: 'Medinan' },
  { number: 3, name: 'آل عمران', englishName: "Ali 'Imran", ayahCount: 200, revelationType: 'Medinan' },
  { number: 4, name: 'النساء', englishName: 'An-Nisa', ayahCount: 176, revelationType: 'Medinan' },
  { number: 5, name: 'المائدة', englishName: "Al-Ma'ida", ayahCount: 120, revelationType: 'Medinan' },
  { number: 6, name: 'الأنعام', englishName: "Al-An'am", ayahCount: 165, revelationType: 'Meccan' },
  { number: 7, name: 'الأعراف', englishName: "Al-A'raf", ayahCount: 206, revelationType: 'Meccan' },
  { number: 8, name: 'الأنفال', englishName: 'Al-Anfal', ayahCount: 75, revelationType: 'Medinan' },
  { number: 9, name: 'التوبة', englishName: 'At-Tawba', ayahCount: 129, revelationType: 'Medinan' },
  { number: 10, name: 'يونس', englishName: 'Yunus', ayahCount: 109, revelationType: 'Meccan' },
  { number: 11, name: 'هود', englishName: 'Hud', ayahCount: 123, revelationType: 'Meccan' },
  { number: 12, name: 'يوسف', englishName: 'Yusuf', ayahCount: 111, revelationType: 'Meccan' },
  { number: 13, name: 'الرعد', englishName: "Ar-Ra'd", ayahCount: 43, revelationType: 'Medinan' },
  { number: 14, name: 'إبراهيم', englishName: 'Ibrahim', ayahCount: 52, revelationType: 'Meccan' },
  { number: 15, name: 'الحجر', englishName: 'Al-Hijr', ayahCount: 99, revelationType: 'Meccan' },
  { number: 16, name: 'النحل', englishName: 'An-Nahl', ayahCount: 128, revelationType: 'Meccan' },
  { number: 17, name: 'الإسراء', englishName: 'Al-Isra', ayahCount: 111, revelationType: 'Meccan' },
  { number: 18, name: 'الكهف', englishName: 'Al-Kahf', ayahCount: 110, revelationType: 'Meccan' },
  { number: 19, name: 'مريم', englishName: 'Maryam', ayahCount: 98, revelationType: 'Meccan' },
  { number: 20, name: 'طه', englishName: 'Ta-Ha', ayahCount: 135, revelationType: 'Meccan' },
  { number: 21, name: 'الأنبياء', englishName: 'Al-Anbiya', ayahCount: 112, revelationType: 'Meccan' },
  { number: 22, name: 'الحج', englishName: 'Al-Hajj', ayahCount: 78, revelationType: 'Medinan' },
  { number: 23, name: 'المؤمنون', englishName: "Al-Mu'minun", ayahCount: 118, revelationType: 'Meccan' },
  { number: 24, name: 'النور', englishName: 'An-Nur', ayahCount: 64, revelationType: 'Medinan' },
  { number: 25, name: 'الفرقان', englishName: 'Al-Furqan', ayahCount: 77, revelationType: 'Meccan' },
  { number: 26, name: 'الشعراء', englishName: "Ash-Shu'ara", ayahCount: 227, revelationType: 'Meccan' },
  { number: 27, name: 'النمل', englishName: 'An-Naml', ayahCount: 93, revelationType: 'Meccan' },
  { number: 28, name: 'القصص', englishName: 'Al-Qasas', ayahCount: 88, revelationType: 'Meccan' },
  { number: 29, name: 'العنكبوت', englishName: "Al-'Ankabut", ayahCount: 69, revelationType: 'Meccan' },
  { number: 30, name: 'الروم', englishName: 'Ar-Rum', ayahCount: 60, revelationType: 'Meccan' },
  { number: 31, name: 'لقمان', englishName: 'Luqman', ayahCount: 34, revelationType: 'Meccan' },
  { number: 32, name: 'السجدة', englishName: 'As-Sajda', ayahCount: 30, revelationType: 'Meccan' },
  { number: 33, name: 'الأحزاب', englishName: 'Al-Ahzab', ayahCount: 73, revelationType: 'Medinan' },
  { number: 34, name: 'سبأ', englishName: 'Saba', ayahCount: 54, revelationType: 'Meccan' },
  { number: 35, name: 'فاطر', englishName: 'Fatir', ayahCount: 45, revelationType: 'Meccan' },
  { number: 36, name: 'يس', englishName: 'Ya-Sin', ayahCount: 83, revelationType: 'Meccan' },
  { number: 37, name: 'الصافات', englishName: 'As-Saffat', ayahCount: 182, revelationType: 'Meccan' },
  { number: 38, name: 'ص', englishName: 'Sad', ayahCount: 88, revelationType: 'Meccan' },
  { number: 39, name: 'الزمر', englishName: 'Az-Zumar', ayahCount: 75, revelationType: 'Meccan' },
  { number: 40, name: 'غافر', englishName: 'Ghafir', ayahCount: 85, revelationType: 'Meccan' },
  { number: 41, name: 'فصلت', englishName: 'Fussilat', ayahCount: 54, revelationType: 'Meccan' },
  { number: 42, name: 'الشورى', englishName: 'Ash-Shura', ayahCount: 53, revelationType: 'Meccan' },
  { number: 43, name: 'الزخرف', englishName: 'Az-Zukhruf', ayahCount: 89, revelationType: 'Meccan' },
  { number: 44, name: 'الدخان', englishName: 'Ad-Dukhan', ayahCount: 59, revelationType: 'Meccan' },
  { number: 45, name: 'الجاثية', englishName: 'Al-Jathiya', ayahCount: 37, revelationType: 'Meccan' },
  { number: 46, name: 'الأحقاف', englishName: 'Al-Ahqaf', ayahCount: 35, revelationType: 'Meccan' },
  { number: 47, name: 'محمد', englishName: 'Muhammad', ayahCount: 38, revelationType: 'Medinan' },
  { number: 48, name: 'الفتح', englishName: 'Al-Fath', ayahCount: 29, revelationType: 'Medinan' },
  { number: 49, name: 'الحجرات', englishName: 'Al-Hujurat', ayahCount: 18, revelationType: 'Medinan' },
  { number: 50, name: 'ق', englishName: 'Qaf', ayahCount: 45, revelationType: 'Meccan' },
  { number: 51, name: 'الذاريات', englishName: 'Adh-Dhariyat', ayahCount: 60, revelationType: 'Meccan' },
  { number: 52, name: 'الطور', englishName: 'At-Tur', ayahCount: 49, revelationType: 'Meccan' },
  { number: 53, name: 'النجم', englishName: 'An-Najm', ayahCount: 62, revelationType: 'Meccan' },
  { number: 54, name: 'القمر', englishName: 'Al-Qamar', ayahCount: 55, revelationType: 'Meccan' },
  { number: 55, name: 'الرحمن', englishName: 'Ar-Rahman', ayahCount: 78, revelationType: 'Medinan' },
  { number: 56, name: 'الواقعة', englishName: "Al-Waqi'a", ayahCount: 96, revelationType: 'Meccan' },
  { number: 57, name: 'الحديد', englishName: 'Al-Hadid', ayahCount: 29, revelationType: 'Medinan' },
  { number: 58, name: 'المجادلة', englishName: 'Al-Mujadila', ayahCount: 22, revelationType: 'Medinan' },
  { number: 59, name: 'الحشر', englishName: 'Al-Hashr', ayahCount: 24, revelationType: 'Medinan' },
  { number: 60, name: 'الممتحنة', englishName: 'Al-Mumtahana', ayahCount: 13, revelationType: 'Medinan' },
  { number: 61, name: 'الصف', englishName: 'As-Saf', ayahCount: 14, revelationType: 'Medinan' },
  { number: 62, name: 'الجمعة', englishName: "Al-Jumu'a", ayahCount: 11, revelationType: 'Medinan' },
  { number: 63, name: 'المنافقون', englishName: 'Al-Munafiqun', ayahCount: 11, revelationType: 'Medinan' },
  { number: 64, name: 'التغابن', englishName: 'At-Taghabun', ayahCount: 18, revelationType: 'Medinan' },
  { number: 65, name: 'الطلاق', englishName: 'At-Talaq', ayahCount: 12, revelationType: 'Medinan' },
  { number: 66, name: 'التحريم', englishName: 'At-Tahrim', ayahCount: 12, revelationType: 'Medinan' },
  { number: 67, name: 'الملك', englishName: 'Al-Mulk', ayahCount: 30, revelationType: 'Meccan' },
  { number: 68, name: 'القلم', englishName: 'Al-Qalam', ayahCount: 52, revelationType: 'Meccan' },
  { number: 69, name: 'الحاقة', englishName: 'Al-Haaqqa', ayahCount: 52, revelationType: 'Meccan' },
  { number: 70, name: 'المعارج', englishName: "Al-Ma'arij", ayahCount: 44, revelationType: 'Meccan' },
  { number: 71, name: 'نوح', englishName: 'Nuh', ayahCount: 28, revelationType: 'Meccan' },
  { number: 72, name: 'الجن', englishName: 'Al-Jinn', ayahCount: 28, revelationType: 'Meccan' },
  { number: 73, name: 'المزمل', englishName: 'Al-Muzzammil', ayahCount: 20, revelationType: 'Meccan' },
  { number: 74, name: 'المدثر', englishName: 'Al-Muddaththir', ayahCount: 56, revelationType: 'Meccan' },
  { number: 75, name: 'القيامة', englishName: 'Al-Qiyama', ayahCount: 40, revelationType: 'Meccan' },
  { number: 76, name: 'الإنسان', englishName: 'Al-Insan', ayahCount: 31, revelationType: 'Medinan' },
  { number: 77, name: 'المرسلات', englishName: 'Al-Mursalat', ayahCount: 50, revelationType: 'Meccan' },
  { number: 78, name: 'النبأ', englishName: 'An-Naba', ayahCount: 40, revelationType: 'Meccan' },
  { number: 79, name: 'النازعات', englishName: "An-Nazi'at", ayahCount: 46, revelationType: 'Meccan' },
  { number: 80, name: 'عبس', englishName: 'Abasa', ayahCount: 42, revelationType: 'Meccan' },
  { number: 81, name: 'التكوير', englishName: 'At-Takwir', ayahCount: 29, revelationType: 'Meccan' },
  { number: 82, name: 'الإنفطار', englishName: 'Al-Infitar', ayahCount: 19, revelationType: 'Meccan' },
  { number: 83, name: 'المطففين', englishName: 'Al-Mutaffifin', ayahCount: 36, revelationType: 'Meccan' },
  { number: 84, name: 'الإنشقاق', englishName: 'Al-Inshiqaq', ayahCount: 25, revelationType: 'Meccan' },
  { number: 85, name: 'البروج', englishName: 'Al-Buruj', ayahCount: 22, revelationType: 'Meccan' },
  { number: 86, name: 'الطارق', englishName: 'At-Tariq', ayahCount: 17, revelationType: 'Meccan' },
  { number: 87, name: 'الأعلى', englishName: "Al-A'la", ayahCount: 19, revelationType: 'Meccan' },
  { number: 88, name: 'الغاشية', englishName: 'Al-Ghashiya', ayahCount: 26, revelationType: 'Meccan' },
  { number: 89, name: 'الفجر', englishName: 'Al-Fajr', ayahCount: 30, revelationType: 'Meccan' },
  { number: 90, name: 'البلد', englishName: 'Al-Balad', ayahCount: 20, revelationType: 'Meccan' },
  { number: 91, name: 'الشمس', englishName: 'Ash-Shams', ayahCount: 15, revelationType: 'Meccan' },
  { number: 92, name: 'الليل', englishName: 'Al-Layl', ayahCount: 21, revelationType: 'Meccan' },
  { number: 93, name: 'الضحى', englishName: 'Ad-Duha', ayahCount: 11, revelationType: 'Meccan' },
  { number: 94, name: 'الشرح', englishName: 'Ash-Sharh', ayahCount: 8, revelationType: 'Meccan' },
  { number: 95, name: 'التين', englishName: 'At-Tin', ayahCount: 8, revelationType: 'Meccan' },
  { number: 96, name: 'العلق', englishName: "Al-'Alaq", ayahCount: 19, revelationType: 'Meccan' },
  { number: 97, name: 'القدر', englishName: 'Al-Qadr', ayahCount: 5, revelationType: 'Meccan' },
  { number: 98, name: 'البينة', englishName: 'Al-Bayyina', ayahCount: 8, revelationType: 'Medinan' },
  { number: 99, name: 'الزلزلة', englishName: 'Az-Zalzala', ayahCount: 8, revelationType: 'Medinan' },
  { number: 100, name: 'العاديات', englishName: "Al-'Adiyat", ayahCount: 11, revelationType: 'Meccan' },
  { number: 101, name: 'القارعة', englishName: "Al-Qari'a", ayahCount: 11, revelationType: 'Meccan' },
  { number: 102, name: 'التكاثر', englishName: 'At-Takathur', ayahCount: 8, revelationType: 'Meccan' },
  { number: 103, name: 'العصر', englishName: "Al-'Asr", ayahCount: 3, revelationType: 'Meccan' },
  { number: 104, name: 'الهمزة', englishName: 'Al-Humaza', ayahCount: 9, revelationType: 'Meccan' },
  { number: 105, name: 'الفيل', englishName: 'Al-Fil', ayahCount: 5, revelationType: 'Meccan' },
  { number: 106, name: 'قريش', englishName: 'Quraysh', ayahCount: 4, revelationType: 'Meccan' },
  { number: 107, name: 'الماعون', englishName: "Al-Ma'un", ayahCount: 7, revelationType: 'Meccan' },
  { number: 108, name: 'الكوثر', englishName: 'Al-Kawthar', ayahCount: 3, revelationType: 'Meccan' },
  { number: 109, name: 'الكافرون', englishName: 'Al-Kafirun', ayahCount: 6, revelationType: 'Meccan' },
  { number: 110, name: 'النصر', englishName: 'An-Nasr', ayahCount: 3, revelationType: 'Medinan' },
  { number: 111, name: 'المسد', englishName: 'Al-Masad', ayahCount: 5, revelationType: 'Meccan' },
  { number: 112, name: 'الإخلاص', englishName: 'Al-Ikhlas', ayahCount: 4, revelationType: 'Meccan' },
  { number: 113, name: 'الفلق', englishName: 'Al-Falaq', ayahCount: 5, revelationType: 'Meccan' },
  { number: 114, name: 'الناس', englishName: 'An-Nas', ayahCount: 6, revelationType: 'Meccan' },
];

const _byNumber = new Map<number, SurahMeta>(SURAH_META.map(s => [s.number, s]));

export function getSurahMeta(surah: number): SurahMeta {
  const meta = _byNumber.get(surah);
  if (!meta) throw new Error(`Invalid surah number: ${surah}`);
  return meta;
}
